### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ParoTheParrot** [kasparsd/rover-editor#2]
After logging in to Dropbox I see my dropbox and an error message. I can't use rover :-(

**Comment by debuti** [comment]
me neither

**Comment by kasparsd** [comment]
You need to use your own Dropbox App key here https://github.com/kasparsd/rover-editor/blob/master/rover.js#L23 and that should solve the problem.

**Comment by debuti** [comment]
Nope. Dropbox library its too old to function correctly with new browsers. I've updated your project to the last version and now it works ok

**Comment by kasparsd** [comment]
Thanks Borja! Could you please do a pull request with the latest library?

**Comment by debuti** [comment]
sure! when i get back home
